### ISSUE TITLE
pydantic.errors.PydanticUserError: Please use `typing_extensions.TypedDict` instead of `typing.TypedDict` on Python < 3.12

### ISSUE THREAD

**Issue by AlothNaveen** [5G-MAG/rt-5gms-application-provider#40]
uvicorn server:app --reload
INFO:     Will watch for changes in these directories: ['/home/naveen/5G-Demo/rt-5gms-application-provider/management-ui']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [159727] using StatReload
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.1) or chardet (5.2.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/type_adapter.py", line 210, in __init__
    core_schema = _getattr_no_parents(type, '__pydantic_core_schema__')
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/type_adapter.py", line 98, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/naveen/.local/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/naveen/.local/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/naveen/.local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/naveen/.local/lib/python3.8/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/naveen/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/naveen/5G-Demo/rt-5gms-application-provider/management-ui/server.py", line 277, in <module>
    async def set_consumption(provisioning_session_id: str, crc: ConsumptionReportingConfiguration):
  File "/home/naveen/.local/lib/python3.8/site-packages/fastapi/routing.py", line 944, in decorator
    self.add_api_route(
  File "/home/naveen/.local/lib/python3.8/site-packages/fastapi/routing.py", line 883, in add_api_route
    route = route_class(
  File "/home/naveen/.local/lib/python3.8/site-packages/fastapi/routing.py", line 513, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/home/naveen/.local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 261, in get_dependant
    type_annotation, depends, param_field = analyze_param(
  File "/home/naveen/.local/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 444, in analyze_param
    field = create_response_field(
  File "/home/naveen/.local/lib/python3.8/site-packages/fastapi/utils.py", line 99, in create_response_field
    return ModelField(**kwargs)  # type: ignore[arg-type]
  File "<string>", line 6, in __init__
  File "/home/naveen/.local/lib/python3.8/site-packages/fastapi/_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/type_adapter.py", line 212, in __init__
    core_schema = _get_schema(type, config_wrapper, parent_depth=_parent_depth + 1)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/type_adapter.py", line 81, in _get_schema
    schema = gen.generate_schema(type_)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 502, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 737, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1752, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1820, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1902, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1898, in <lambda>
    lambda source, handler: handler(source)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1801, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 758, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 806, in match_type
    return self._typed_dict_schema(obj, None)
  File "/home/naveen/.local/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 1228, in _typed_dict_schema
    raise PydanticUserError(
pydantic.errors.PydanticUserError: Please use `typing_extensions.TypedDict` instead of `typing.TypedDict` on Python < 3.12.

For further information visit https://errors.pydantic.dev/2.7/u/typed-dict-version

**Comment by dsilhavy** [comment]
Did you try upgrading to the latest python version 3.12.3? As the error message indicates, it seems to be a problem with older Python versions. It works fine for me with 3.12.3

**Comment by AlothNaveen** [comment]
Yes, It's working. But it has to work with other python versions like 3.8.10 right?

**Comment by dsilhavy** [comment]
@stojkovicv Any opinion on this. What is the effort to make this backwards compatible with older Python versions?

**Comment by stojkovicv** [comment]
We can import library in two different ways depending on the system's Python version, but I don't recommend this. I think we should keep project up to date with the latest Python versions.

Multiple Python versions can be installed in the system and managed with the virtual environment properly, for example:
```
python3.12 -m venv management-ui
```
